css/pages/home.css
index.html
js/pages/home.js

Template commit

---

css/base/layout.css

Clean HTML

---

css/base/layout.css

responsive design css update (layout)

layout css

---

index.html

Metrics responsive

---

index.html

Header responsive and template

Header responsive

---

index.html

First stage of responsive for Creative section. Will be updated with more info next time.

Creative responsive

---

css/base/layout.css

Backround colours removed

---

index.html

I added Choose us section responsive code, because it was mising out

responsive code correction

---

css/base/base.css
css/pages/home.css
index.html

- updated font-styles
- updated font-colors

update general style

---

css/components/contact.css
css/pages/home.css
index.html

Call us with number and button was added

Header contact button

---

index.html

Latest responsive update

---

css/base/base.css
css/components/hero.css
index.html

Buttons styling, imges positioning

Hero details styling

---

css/components/contact.css
css/pages/home.css
index.html
js/pages/home.js

Sticky Header Javascript

---

css/components/hero.css
index.html

creating and positioning hero lord-icon

hero lord icon

---

css/components/blog.css
css/components/button.css
css/pages/home.css
index.html

Added blog issues and button css class for all home page

Blog text and button

---

css/components/brands.css

Fixed responsive and img csss media

Brands styling and media

---

css/components/button.css
css/components/latest.css
css/pages/home.css
index.html

Added navy button to button.css
Done some changes in Latest section. Not finished.

Latest img text and button.css

---

css/components/latest.css

Small detail, but visually looks better.

Styling update

---

css/components/creative.css
index.html

Creative styling

---

js/components/header.js
js/pages/home.js

home.js code transferred to header.js

Header JS structural transfer

---

css/components/hero.css
index.html
js/components/hero-heading-text.js

Hero heading typewriter added, last sentence changing

Hero heading animation

---

index.html

Button fix #2

---

css/components/blog.css
css/components/signup.css
css/pages/home.css
index.html

- Choose us button fix
- Signup form on focus border removed
- Blog button fix
- Blog top img removed for the time being because had a bottom scroll straight from website opening

choose us button fix, signup form, blog button fix

---

css/components/checks.css
css/pages/home.css
index.html

Menu checks created on:
[Home][Pages][Mega Menu][Blog][Shop]

Header menu checks

---

css/components/checks.css
css/components/header.css
css/components/submenu.css
css/pages/home.css
index.html
js/pages/home.js

Header was on top left, fixed to position. 
Menu submenu was opening wrong, fixed.
Submenu checks was gone. Added again.

Header and sumbenu fixed

---

css/components/header.css
css/components/submenu.css

Submenu design

---

index.html

Was effecting responsive design. Temporary "off".

Latest dot icon remove
